---
title: "Artificial Neural Network (ANN) for predicting Heart Attack"
output: html_notebook
---

```{r}
# Importing the dataset
dataset = read.csv('Heart.csv')
dataset = data.frame(dataset[-1])
dim(dataset)
str(dataset)

# Checking for missing data
d3=dataset
for(i in 1:ncol(d3))
   {
    print(colnames(d3[i]))
    print(sum(is.na(d3[i])))
}

# Some missing data is present
# Removing Missing Data from data set
dataset = na.omit(dataset)
dim(dataset)

# Checking for missing data again
d3=dataset
for(i in 1:ncol(d3))
   {
    print(colnames(d3[i]))
    print(sum(is.na(d3[i])))
}

# Encoding the categorical & numerical variables in dataset
dataset$Age = as.numeric(dataset$Age)
dataset$Sex = as.factor(dataset$Sex)
dataset$ChestPain = as.factor(dataset$ChestPain)
dataset$RestBP = as.numeric(dataset$RestBP)
dataset$Chol = as.numeric(dataset$Chol)
dataset$Fbs = as.factor(dataset$Fbs)
dataset$RestECG = as.factor(dataset$RestECG)
dataset$MaxHR = as.numeric(dataset$MaxHR)
dataset$ExAng = as.factor(dataset$ExAng)
dataset$Oldpeak = as.numeric(dataset$Oldpeak)
dataset$Slope = as.factor(dataset$Slope)
dataset$Ca = as.factor(dataset$Ca)
dataset$Thal = as.factor(dataset$Thal)

dataset$AHD = ifelse(dataset$AHD == "Yes",1,0)
dataset$AHD = as.factor(dataset$AHD)

str(dataset)

```

```{r}

# Splitting the dataset into the Training set and Test set

library(caTools)
set.seed(123)
split = sample.split(dataset$AHD, SplitRatio = 0.75)
training_set = subset(dataset, split == TRUE)
test_set = subset(dataset, split == FALSE)

# Feature Scaling
training_set[,c(1,4,5,8,10)] = scale(training_set[,c(1,4,5,8,10)])
test_set[,c(1,4,5,8,10)] = scale(test_set[,c(1,4,5,8,10)])


```


```{r}
# Fitting ANN to the Training set
# Nodes in hidden layers selected by Avg (# Input + # Output Nodes) = (14+1)/2 =  7.5; 8
#install.packages('h2o')
library(h2o)
h2o.init(ip = "localhost")
model = h2o.deeplearning(y = 14,
                         training_frame = as.h2o(training_set),
                         activation = 'Rectifier',
                         hidden = c(8,8),
                         epochs = 100,
                         train_samples_per_iteration = -2)

# Predicting the Test set results
y_pred = h2o.predict(model, newdata = as.h2o(test_set[-14]))
str(y_pred)
dim(test_set)

y_pred=y_pred[1]
y_pred = as.vector(y_pred)

# Making the Confusion Matrix
cm = table(test_set[, 14], y_pred)
print(cm)

Model_Accuracy=(cm[1,1]+cm[2,2])/(cm[1,1]+cm[1,2]+cm[2,1]+cm[2,2])

print(" Model Accuracy is") 
print(Model_Accuracy)

# Model Accuracy is 81% which seems quite good.

h2o.shutdown()

```



```

